logging:
  spec: info
  format: "%{color}%{time:15:04:05.000} [%{module}] %{shortfunc} %{level:.4s}%{color:reset} %{message}"

fsc:
  id: endorser1
  identity:
    cert:
      file: ./keys/node.crt
    key:
      file: ./keys/node.key
  p2p:
    listenAddress: /ip4/0.0.0.0/tcp/9301
    type: websocket
    opts:
      routing:
        path: ./routing-config.yaml
  persistences:
    default:
      type: sqlite
      opts:
        dataSource: file:./data/fts.sqlite
  endpoint:
    resolvers:
      - name: issuer
        identity:
          id: issuer
          path: ./keys/nodes/issuer.crt
        addresses:
          P2P: issuer.example.com:9101
      - name: endorser1
        identity:
          id: endorser1
          path: ./keys/nodes/endorser1.crt
        addresses:
          P2P: endorser1.example.com:9301
      - name: owner1
        identity:
          id: owner1
          path: ./keys/nodes/owner1.crt
        addresses:
          P2P: owner1.example.com:9501

fabric:
  enabled: true
  default:
    driver: fabricx
    msps:
      - id: endorser
        mspType: bccsp
        mspID: Org1MSP
        path: ./keys/fabric/user
    tls:
      enabled: false
    peers:
      - address: committer-sidecar:4001
        usage: delivery
    queryService:
      - address: committer-queryservice:7001
    channels:
      - name: arma
        default: true

token:
  enabled: true
  tms:
    mytms:
      network: default
      channel: arma
      namespace: token_namespace
      driver: zkatdlog
      services:
        network:
          fabric:
            fsc_endorsement:
              endorser: true
              id: endorser
              policy:
                type: all
              endorsers:
                - endorser1
      publicParameters:
        path: ../namespace/zkatdlognoghv1_pp.json
